name: "NASA Project CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa

    strategy:
      matrix:
        node-version: [20.x, 21.x]
        mongodb-version: [8.0]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.11.0
      - name: Install client dependencies and build client
        run: npm install
        working-directory: ./client

      - name: Install server dependencies
        run: npm install
        working-directory: ./server
