name: "NASA Project CI"
on:
  push:
    branches: [master]
    pull_request: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
        
        - name: Install client dep and build client
          run: npm install
          working-directory: ./client
        
        - name: install server dep 
          run: npm install
          working-directory: ./server